name: ActionLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Rhysd actionlint
        uses: devops-actions/actionlint@48ca80d7da4ffd5ed31b7981702bc6bb4b242c63 # v0.1.2
        continue-on-error: true
        id: action-lint
        
      - name: Upload results
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: actionlint-results
          path: ${{ steps.action-lint.outputs.results-file }}
