name: ActionLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Rhysd actionlint
        uses: devops-actions/actionlint@48ca80d7da4ffd5ed31b7981702bc6bb4b242c63 # v0.1.2
        continue-on-error: true
        id: action-lint
        
      - name: Upload results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: actionlint-results
          path: ${{ steps.action-lint.outputs.results-file }}
