name: ActionLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Rhysd actionlint
        uses: devops-actions/actionlint@v0.1.2
        continue-on-error: true
        id: action-lint
        
      - name: Upload results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: actionlint-results
          path: ${{ steps.action-lint.outputs.results-file }}
